name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want to use

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler
          gem install jekyll

      - name: Build Jekyll site
        run: |
          jekyll build

      - name: Deploy
        run: |
          # Add your deployment commands here, if necessary
