name: Jekyll Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version you need
          bundler-cache: true   # Cache installed gems to speed up builds

      - name: Set GEM_HOME
        run: |
          echo "GEM_HOME=$HOME/.gem" >> $GITHUB_ENV
          echo "PATH=$HOME/.gem/bin:$PATH" >> $GITHUB_ENV

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Output directory for Jekyll build
